"""Online semantic_weight tuning (v1.23.0).

Reads `ranking_events` from `~/.doc-index/telemetry.db` for one repo
(or every repo), splits events by `semantic_used`, compares mean
confidence with vs without the semantic channel, and proposes a
±0.05 step on the per-repo `semantic_weight` when the gap is large
enough to act on.

Bounded:

  - `min_events` (default 50) gates against overfitting on a few
    early calls.
  - Step size ±0.05 keeps drift gradual; clamped to [0.10, 0.85] so
    we never fully disable either channel.
  - Threshold |delta_conf| >= 0.05 — smaller swings stay flat.

Persisted at `~/.doc-index/tuning.jsonc`:

    {
      "repos": {
        "<owner>/<name>": {
          "semantic_weight": 0.55,
          "learned_from_events": 312,
          "captured_at": "2026-04-26T13:42:11Z"
        },
        ...
      }
    }

Mirrors jcodemunch v1.79.0 in shape; pure-Python, no numpy.
"""

from __future__ import annotations

import json
import re
import threading
import time
from pathlib import Path
from typing import Optional

from ..storage.token_tracker import ranking_db_query

DEFAULT_SEMANTIC_WEIGHT = 0.5
SEMANTIC_WEIGHT_BOUNDS = (0.10, 0.85)
MIN_EVENTS = 50
DELTA_CONF_THRESHOLD = 0.05
STEP = 0.05

_TUNING_FILENAME = "tuning.jsonc"
_TUNING_LOCK = threading.Lock()
_TUNING_CACHE: dict = {}
_TUNING_CACHE_PATH: Optional[str] = None


def _tuning_path(base_path: Optional[str] = None) -> Path:
    root = Path(base_path) if base_path else Path.home() / ".doc-index"
    root.mkdir(parents=True, exist_ok=True)
    return root / _TUNING_FILENAME


def _strip_jsonc(text: str) -> str:
    """Strip // and /* */ comments before json.loads."""
    text = re.sub(r"/\*.*?\*/", "", text, flags=re.DOTALL)
    text = re.sub(r"//[^\n]*", "", text)
    return text


def _load(base_path: Optional[str] = None) -> dict:
    global _TUNING_CACHE, _TUNING_CACHE_PATH
    path = _tuning_path(base_path)
    path_str = str(path)
    with _TUNING_LOCK:
        if _TUNING_CACHE_PATH == path_str and _TUNING_CACHE:
            return _TUNING_CACHE
        if not path.exists():
            _TUNING_CACHE = {"repos": {}}
            _TUNING_CACHE_PATH = path_str
            return _TUNING_CACHE
        try:
            raw = path.read_text(encoding="utf-8")
            data = json.loads(_strip_jsonc(raw))
            if not isinstance(data, dict):
                data = {"repos": {}}
            data.setdefault("repos", {})
            _TUNING_CACHE = data
            _TUNING_CACHE_PATH = path_str
            return _TUNING_CACHE
        except Exception:
            _TUNING_CACHE = {"repos": {}}
            _TUNING_CACHE_PATH = path_str
            return _TUNING_CACHE


def _persist(data: dict, base_path: Optional[str] = None) -> None:
    global _TUNING_CACHE, _TUNING_CACHE_PATH
    path = _tuning_path(base_path)
    header = (
        "// jdocmunch tuning overrides — auto-generated by tune_weights.\n"
        "// Hand-edits are preserved (JSONC: line and block comments allowed).\n"
    )
    body = json.dumps(data, indent=2)
    tmp = path.with_suffix(path.suffix + ".tmp")
    with _TUNING_LOCK:
        tmp.write_text(header + body + "\n", encoding="utf-8")
        tmp.replace(path)
        _TUNING_CACHE = data
        _TUNING_CACHE_PATH = str(path)


def reset_cache() -> None:
    """Test hook — invalidate the in-memory cache."""
    global _TUNING_CACHE, _TUNING_CACHE_PATH
    with _TUNING_LOCK:
        _TUNING_CACHE = {}
        _TUNING_CACHE_PATH = None


def get_semantic_weight(
    repo: str,
    *,
    explicit: Optional[float] = None,
    base_path: Optional[str] = None,
) -> float:
    """Resolve the semantic_weight for a repo.

    Resolution priority:
      1. Explicit non-default caller value (anything that isn't ``None``
         and isn't exactly the v1.13 default 0.5).
      2. Tuning override loaded from ``tuning.jsonc``.
      3. Default 0.5.
    """
    if explicit is not None and explicit != DEFAULT_SEMANTIC_WEIGHT:
        return float(explicit)
    data = _load(base_path)
    repos = data.get("repos") or {}
    entry = repos.get(repo) or {}
    val = entry.get("semantic_weight")
    if isinstance(val, (int, float)):
        lo, hi = SEMANTIC_WEIGHT_BOUNDS
        return max(lo, min(hi, float(val)))
    return DEFAULT_SEMANTIC_WEIGHT


def _clamp(val: float) -> float:
    lo, hi = SEMANTIC_WEIGHT_BOUNDS
    return max(lo, min(hi, val))


def tune_one_repo(
    repo: str,
    *,
    min_events: int = MIN_EVENTS,
    dry_run: bool = False,
    base_path: Optional[str] = None,
) -> dict:
    """Compute and (optionally) persist a tuned weight for one repo."""
    events = ranking_db_query(repo=repo, limit=10000, base_path=base_path)
    n = len(events)
    if n < min_events:
        return {
            "repo": repo,
            "status": "insufficient_events",
            "events_seen": n,
            "min_events": min_events,
        }

    confidences_with: list[float] = []
    confidences_without: list[float] = []
    for e in events:
        c = e.get("confidence")
        if c is None:
            continue
        if e.get("semantic_used"):
            confidences_with.append(float(c))
        else:
            confidences_without.append(float(c))

    if not confidences_with or not confidences_without:
        return {
            "repo": repo,
            "status": "no_signal_split",
            "events_seen": n,
            "with_semantic": len(confidences_with),
            "without_semantic": len(confidences_without),
        }

    mean_with = sum(confidences_with) / len(confidences_with)
    mean_without = sum(confidences_without) / len(confidences_without)
    delta = mean_with - mean_without

    data = _load(base_path)
    repos = data.setdefault("repos", {})
    current = float((repos.get(repo) or {}).get("semantic_weight", DEFAULT_SEMANTIC_WEIGHT))

    if delta >= DELTA_CONF_THRESHOLD:
        proposed = _clamp(current + STEP)
        decision = "semantic_helps"
    elif delta <= -DELTA_CONF_THRESHOLD:
        proposed = _clamp(current - STEP)
        decision = "semantic_hurts"
    else:
        return {
            "repo": repo,
            "status": "no_significant_signal",
            "events_seen": n,
            "delta_confidence": round(delta, 4),
            "mean_with_semantic": round(mean_with, 4),
            "mean_without_semantic": round(mean_without, 4),
            "current_semantic_weight": current,
        }

    if not dry_run:
        repos[repo] = {
            "semantic_weight": proposed,
            "learned_from_events": n,
            "captured_at": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
        }
        _persist(data, base_path)

    return {
        "repo": repo,
        "status": decision,
        "events_seen": n,
        "delta_confidence": round(delta, 4),
        "mean_with_semantic": round(mean_with, 4),
        "mean_without_semantic": round(mean_without, 4),
        "previous_semantic_weight": current,
        "new_semantic_weight": proposed,
        "dry_run": dry_run,
    }


def tune_all_repos(
    *,
    min_events: int = MIN_EVENTS,
    dry_run: bool = False,
    base_path: Optional[str] = None,
) -> list[dict]:
    """Tune every repo that has any events. Empty list when none."""
    events = ranking_db_query(limit=100000, base_path=base_path)
    repos = sorted({e.get("repo") for e in events if e.get("repo")})
    return [tune_one_repo(repo=r, min_events=min_events, dry_run=dry_run, base_path=base_path) for r in repos]
