"""Repo-group configuration store (v1.26.0).

A *repo group* is a named alias that maps to a list of indexed repo
identifiers. Used by ``search_sections(repo_group=...)`` to fan out a
single query across constituent repos and fuse the results via RRF.

Persisted at ``~/.doc-index/_groups.jsonc``:

    {
      "groups": {
        "docs-everywhere": ["python-docs", "internal-runbook", "openapi-spec"],
        "platform": ["frontend-docs", "backend-docs"]
      }
    }

JSONC: line and block comments tolerated. Atomic write via tmp + replace.
"""

from __future__ import annotations

import json
import re
import threading
from pathlib import Path
from typing import Optional

_FILENAME = "_groups.jsonc"
_LOCK = threading.Lock()


def _path(base_path: Optional[str] = None) -> Path:
    root = Path(base_path) if base_path else Path.home() / ".doc-index"
    root.mkdir(parents=True, exist_ok=True)
    return root / _FILENAME


def _strip_jsonc(text: str) -> str:
    text = re.sub(r"/\*.*?\*/", "", text, flags=re.DOTALL)
    text = re.sub(r"//[^\n]*", "", text)
    return text


def load(base_path: Optional[str] = None) -> dict:
    """Return the parsed groups dict, or an empty default."""
    path = _path(base_path)
    if not path.exists():
        return {"groups": {}}
    try:
        raw = path.read_text(encoding="utf-8")
        data = json.loads(_strip_jsonc(raw))
        if not isinstance(data, dict):
            return {"groups": {}}
        data.setdefault("groups", {})
        # Filter to dict-of-list-of-str shape; tolerate junk values.
        clean: dict[str, list[str]] = {}
        for k, v in (data["groups"] or {}).items():
            if isinstance(k, str) and isinstance(v, list):
                clean[k] = [r for r in v if isinstance(r, str) and r]
        return {"groups": clean}
    except Exception:
        return {"groups": {}}


def write(data: dict, base_path: Optional[str] = None) -> None:
    """Atomically rewrite the groups config."""
    path = _path(base_path)
    tmp = path.with_suffix(path.suffix + ".tmp")
    header = (
        "// jdocmunch repo-group config — auto-generated by define_repo_group.\n"
        "// Hand-edits welcome (JSONC: line and block comments allowed).\n"
    )
    body = json.dumps({"groups": data.get("groups", {})}, indent=2)
    with _LOCK:
        tmp.write_text(header + body + "\n", encoding="utf-8")
        tmp.replace(path)


def define(name: str, repos: list[str], base_path: Optional[str] = None) -> dict:
    """Create or replace one group. Empty repos list deletes."""
    data = load(base_path)
    groups = data["groups"]
    repos_clean = [r for r in repos if isinstance(r, str) and r.strip()]
    if not repos_clean:
        groups.pop(name, None)
    else:
        groups[name] = repos_clean
    write(data, base_path)
    return data


def list_groups(base_path: Optional[str] = None) -> dict[str, list[str]]:
    return load(base_path)["groups"]


def resolve(name: str, base_path: Optional[str] = None) -> list[str]:
    """Return the constituent repos for a group, or [] when undefined."""
    return list_groups(base_path).get(name) or []
